evanavi/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("user/", include("user.urls"))
]

main/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "main"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("user_register/",views.user_data_view, name="user_register"),
    path("eva/",views.eva_view, name="eva"),
    # path("status/", views.status_view, name="status"),
    path("status/radar_chart/", views.radar_chart_view, name="radar_chart"),
    path("jobs/", views.job_list_view, name="job_list"),
    path("eva_list/", EvaluationListView.as_view(), name="eva_list"),
    path("generate/", views.generate_self_promotion, name="generate_self_promotion"),
    path('download_self_promotion/<str:format>/', views.download_self_promotion, name='download_self_promotion'),
]

user/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('signin/', views.LoginView.as_view(), name="signin"),
#    path('signout/', views.LogoutView.as_view(), name="signout"),
    path('signout/', views.signout, name="signout"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

#ログイン用モデル
class User(AbstractBaseUser, PermissionsMixin):
    user_vali = UnicodeUsernameValidator()
    username = models.CharField(_('username'), max_length=150, unique=True, validators=[user_vali])
    email = models.EmailField(_('email'), unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class UserCreationForm(UserCreationForm):
    class Meta:
        def __init__(self, *args, **kwargs ):
            super().__init__(*args, **kwargs)
            self.fields['model'].widget.attrs['class'] = 'box'
        model = User
        fields = ("username", "email")
        labels = {
            "username": "ユーザー名",
            "email": "メールアドレス",
        }
        
class LoginForm(AuthenticationForm):
    class Meta:
        model = User

user/views.py
from django.views.generic import CreateView, TemplateView
from django.http import HttpResponseRedirect
from .forms import UserCreationForm
from django.urls import reverse,reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from .forms import LoginForm
# Create your views here.
class SignUpView(CreateView):

    form_class = UserCreationForm

    template_name = "user/signup.html"

    success_url = reverse_lazy('user:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = "user/signup_success.html"
    
class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = "user/signin.html"

#    class LogoutView(BaseLogoutView):
#        success_url = reverse_lazy("user:signin")

def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse("user:signin"))

user/templates/user/signin.html
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <div class="form-container">
        <img src="{% static "media/logo/Eva.png" %}" width=300 height=100 alt="エヴァナビロゴ" class="logo">
        <h3>▼--<span id="signin">login</span>--▼</h3>

        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {{ field.label }}
            <br>
            {{ field }}
            <br>
            {{ field.errors }}
            <br>
            {% endfor %}
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Login</button>
                <a href="{% url 'main:home' %}" class="btn btn-secondary">Back</a>
            </div>
            
        </form>
    </div>

user/templates/user/signup.html
{% load static %}
{% load widget_tweaks %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <div class="form-container">
    <div class="container">

      <div class="row justify-content-center">

        <div class="col-md-8 col-lg-6">
          
          <img src="{% static "media/logo/Eva.png" %}" width=300 height=100 alt="エヴァナビロゴ" class="logo">
          <h3>▼--<span id="signup">サインアップ</span>--▼</h3>
          
            <br>
              <form method="post" class="box">
                
                {% csrf_token %}

                {% for field in form %}
                <p>
                  {{ field.label_tag }}<br>
                  {{ field }}<br>
                  {% if field.help_text %}
                  <small style="color: grey" >{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </p>
                {% endfor %}

                <p style="color:red">
                  ※<span id="required_email">メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。</span>
                </p>

                <input type="submit" value="Sign up" class="signup-button">
                
              </form>
            <br>
          
            
          <p>
            <a href="{% url 'main:home' %}">
              <span id="back">トップへ</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>

user/templates/user/signup_success.html
<div class="container">

    <div class="row">


        <div class="col offset-4 py-4">
            <h3><span id="complete">登録が完了しました!</span></h3>
            <br>
            <p><a href="{% url 'user:signin' %}"><span id="login">ログインはこちら</span></a></p>
        </div>
    </div>
</div>